# Initialize new container using official Ubuntu base image
FROM ubuntu

# Set home directory & copy project source code
ENV HOME="/home"
COPY . $HOME/repos/{{project_name}}
WORKDIR $HOME

# Install OS packages
RUN apt-get update
RUN xargs -a $HOME/repos/granite/packages.txt apt-get install -y

# Install Python packages
ENV PYTHON_VERSION=3.11.9
ENV PYENV_ROOT="$HOME/.pyenv"
ENV PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"
RUN set -ex \
    && curl https://pyenv.run | bash \
    && pyenv update \
    && pyenv install $PYTHON_VERSION \
    && pyenv global $PYTHON_VERSION \
    && pyenv rehash

# Run tail command so container stays alive
CMD ["tail", "-f", "/dev/null"]
