# 		{{project_name}}
#		~~~~~~~~~~~~~~~~
# 		Makefile for ``{{project_name}}`` Python project.
# 		Use these commands to build your local development environment.
#
help:
	@echo -e "\
	\n Available commands: 									  \
	\n													      \
    \n   $ make <COMMAND> 									  \
    \n   e.g., $ make setup    							      \
    \n														  \
	\n   setup: initialize local development environment      \
	\n   docker: start a Docker container in the background   \
	\n   dependencies: install Python and OS dependencies     \
	\n   linter: start pre-commit hook with Ruf linter        \
	\n   docs: generate Sphinx documentation from code        \
	"


.PHONY: setup
setup: docker_init
	echo 'initialize local development environment ... '


.PHONY: docker_init
docker_init:
	echo 'initializing Docker image and running a new container ...'
	docker build -t {{project_name}} .
	docker run -d --name {{project_name}}_container {{project_name}}


.PHONY: docker_start
docker_start:
	docker start {{project_name}}_container


.PHONY: docker_stop
docker_stop:
	docker stop {{project_name}}_container


.PHONY: docker_clean
docker_clean:
    echo 'Stopping ...'
    docker stop {{project_name}}_container
    docker container rm -f {{project_name}}_container
    docker image rm -f {{project_name}}
